Repository carpool-team/carpool, pull requests merged in 2021-01, with the labels that each got.

#109 feat: removing ride requests
  src/API/RestService/RestApi/Commands/RideRequestCommands/ResignRideRequestCommand.cs
  src/API/RestService/RestApi/Controllers/RideRequestsController.cs
Labels: enhancement

#110 Hotfix/web/routing
  src/Web/src/components/map/MapBoxGroups.tsx
  src/Web/src/components/map/MapBoxInvites.tsx
  src/Web/src/components/map/MapBoxRides.tsx
  src/Web/src/components/navBar/NavBar.tsx
  src/Web/src/components/navBar/navButton/NavButton.tsx
  src/Web/src/helpers/UniversalHelper.ts
Labels: bug

#114 Przechowywanie tokena miedzy sesjami
  .github/workflows/azure-static-web-apps-yellow-river-01444fd03.yml
  src/Web/src/App.tsx
  src/Web/src/components/auth/store/Actions.ts
  src/Web/src/components/auth/store/Epics.ts
  src/Web/src/components/auth/store/Types.ts
  src/Web/src/components/helpForm/HelpForm.tsx
  src/Web/src/components/layout/Layout.tsx
  src/Web/src/components/layout/store/PropsTypes.ts
Labels: enhancement

#115 Obsługa odświeżania tokena
  src/Web/src/api/Helper.ts
  src/Web/src/api/enum/RequestEndpoint.ts
  src/Web/src/api/enum/RequestType.ts
  src/Web/src/api/requests/RequestCore.ts
  src/Web/src/components/auth/api/login/LoginRequest.ts
  src/Web/src/components/auth/api/register/RegisterRequest.ts
  src/Web/src/components/groups/api/addGroup/AddGroupRequest.ts
  src/Web/src/components/groups/api/addInvite/AddInviteRequest.ts
  src/Web/src/components/groups/api/addRide/AddRideRequest.ts
  src/Web/src/components/groups/api/answerInvite/AnswerInviteRequest.ts
  src/Web/src/components/groups/api/getGroups/GetGroupsRequest.ts
  src/Web/src/components/groups/api/getInvites/GetInvitesRequest.ts
  src/Web/src/components/groups/api/getRides/GetRidesRequest.ts
  src/Web/src/components/groups/api/participateInRide/ParticipateInRideRequest.ts
  src/Web/src/components/groups/api/updateGroup/UpdateGroupRequest.ts
  src/Web/src/components/groups/api/userAutocomplete/UserAutocompleteRequest.ts
  src/Web/src/components/rides/api/addRideRequest/AddRideRequestRequest.ts
  src/Web/src/components/rides/api/getRideRequests/GetRideRequestsRequest.ts
  src/Web/src/components/rides/api/updateRideRequest/UpdateRideRequestRequest.ts
  src/Web/src/components/userProfile/api/GetDataRequest.ts
  src/Web/src/components/userProfile/api/UpdateDataRequest.ts
Labels: enhancement

#118 fix: Zachowanie przy odczycie zapisanego tokena
  src/Web/package-lock.json
  src/Web/package.json
  src/Web/src/helpers/UniversalHelper.ts
Labels: bug, enhancement

#120 fix: Błąd z cyklicznym odwołaniem
  src/Web/src/api/requests/RequestCore.ts
Labels: bug

#121 feat: Obsługa żądań przejazdów i odpowiedzi po stronie kierowcy.
  src/Web/src/api/Helper.ts
  src/Web/src/api/enum/RequestEndpoint.ts
  src/Web/src/api/requests/RequestCore.ts
  src/Web/src/components/groups/Groups.tsx
  src/Web/src/components/groups/api/getRides/GetRidesRequest.ts
  src/Web/src/components/groups/api/getRides/GetRidesResponse.ts
  src/Web/src/components/groups/api/participateInRide/ParticipateInRideRequest.ts
  src/Web/src/components/groups/api/participateInRide/ParticipateInRideResponse.ts
  src/Web/src/components/groups/components/GroupsRouter.tsx
  src/Web/src/components/groups/components/addGroupForm/AddGroupForm.tsx
  src/Web/src/components/groups/components/addGroupForm/components/Form.tsx
  src/Web/src/components/groups/components/detailedView/GroupDetailedView.tsx
  src/Web/src/components/groups/components/edit/GroupEdit.tsx
  src/Web/src/components/groups/components/rides/GroupRides.tsx
  src/Web/src/components/groups/interfaces/IGroup.ts
  src/Web/src/components/groups/interfaces/IGroupCallbacks.ts
  src/Web/src/components/groups/interfaces/IRide.ts
  src/Web/src/components/groups/interfaces/IRideRequest.ts
  src/Web/src/components/groups/interfaces/rideRequest/IRideRequestRide.ts
  src/Web/src/components/groups/store/Actions.ts
  src/Web/src/components/groups/store/Epics.ts
  src/Web/src/components/groups/store/PropsTypes.ts
  src/Web/src/components/groups/store/Reducers.ts
  src/Web/src/components/groups/store/State.ts
  src/Web/src/components/groups/store/Types.ts
  src/Web/src/components/map/MapBoxRides.tsx
  src/Web/src/components/rides/api/addRideRequest/AddRideRequestRequest.ts
  src/Web/src/components/rides/components/addRide/AddRide.tsx
  src/Web/src/components/rides/components/rideRequest/RideRequest.tsx
  src/Web/src/components/rides/store/Actions.ts
  src/Web/src/components/rides/store/Epics.ts
  src/Web/src/components/rides/store/PropsTypes.ts
  src/Web/src/components/rides/store/Reducers.ts
  src/Web/src/components/rides/store/Types.ts
  src/Web/src/components/shared/addressModal/AddressModal.scss
  src/Web/src/components/shared/addressModal/AddressModal.tsx
  src/Web/src/components/shared/ridesList/RidesList.tsx
  src/Web/src/components/shared/ridesList/components/items/ActiveItemDefault.tsx
  src/Web/src/components/shared/ridesList/components/items/ActiveItemJoin.tsx
  src/Web/src/components/shared/ridesList/components/items/ActiveItemRequestOwner.tsx
  src/Web/src/components/shared/ridesList/components/lists/RidesListDefault.tsx
  src/Web/src/components/shared/ridesList/components/lists/RidesListSchedule.tsx
  src/Web/src/components/shared/ridesList/interfaces/IListProps.ts
  src/Web/src/components/shared/ridesList/interfaces/IRidesItemProps.ts
  src/Web/src/components/shared/ridesList/interfaces/IRidesListProps.ts
  src/Web/src/components/userProfile/components/UserData.tsx
  src/Web/src/examples/exampleGroups.ts
  src/Web/src/examples/exampleRidesRequest.ts
  src/Web/src/translations/pl.json
  src/Web/tsconfig.json
  src/Web/webpack.common.js
Labels: enhancement

#126 feature: [WEB] Opuszczanie przejazdu
  src/Web/src/api/Helper.ts
  src/Web/src/api/enum/RequestEndpoint.ts
  src/Web/src/components/groups/components/manageScreen/components/groupsList/GroupsList.tsx
  src/Web/src/components/groups/store/Epics.ts
  src/Web/src/components/rides/api/addRide/AddRideRequestRequest.ts
  src/Web/src/components/rides/api/addRide/AddRideRequestResponse.ts
  src/Web/src/components/rides/api/getRide/GetRideRequestsRequest.ts
  src/Web/src/components/rides/api/getRide/GetRideRequestsResponse.ts
  src/Web/src/components/rides/api/leaveRide/LeaveRideRequest.ts
  src/Web/src/components/rides/api/leaveRide/LeaveRideResponse.ts
  src/Web/src/components/rides/api/updateRide/UpdateRideRequestRequest.ts
  src/Web/src/components/rides/api/updateRide/UpdateRideRequestResponse.ts
  src/Web/src/components/rides/store/Actions.ts
  src/Web/src/components/rides/store/Epics.ts
  src/Web/src/components/rides/store/Types.ts
  src/Web/src/components/shared/ridesList/components/items/ActiveItemParticipant.tsx
  src/Web/src/components/shared/ridesList/components/lists/RidesListSchedule.tsx
Labels: enhancement

#127 feature: [WEB] Usuwanie konta
  src/Web/src/api/Helper.ts
  src/Web/src/api/enum/RequestEndpoint.ts
  src/Web/src/components/layout/components/LayoutRouter.tsx
  src/Web/src/components/userProfile/api/UpdateDataResponse.ts
  src/Web/src/components/userProfile/api/deleteUser/DeleteUserRequest.ts
  src/Web/src/components/userProfile/api/deleteUser/DeleteUserResponse.ts
  src/Web/src/components/userProfile/api/getData/GetDataRequest.ts
  src/Web/src/components/userProfile/api/getData/GetDataResponse.ts
  src/Web/src/components/userProfile/api/updateData/UpdateDataRequest.ts
  src/Web/src/components/userProfile/api/updateData/UpdateDataResponse.ts
  src/Web/src/components/userProfile/components/UserData.tsx
  src/Web/src/components/userProfile/store/Actions.ts
  src/Web/src/components/userProfile/store/Epics.ts
  src/Web/src/components/userProfile/store/PropsTypes.ts
  src/Web/src/components/userProfile/store/Types.ts
Labels: enhancement

#129 feature: [WEB] Usuwanie grupy
  src/Web/src/components/groups/api/deleteGroup/DeleteGroupRequest.ts
  src/Web/src/components/groups/api/deleteGroup/DeleteGroupResponse.ts
  src/Web/src/components/groups/components/edit/components/EditGroupForm.tsx
  src/Web/src/components/groups/components/users/components/UsersGroupForm.tsx
  src/Web/src/components/groups/store/Actions.ts
  src/Web/src/components/groups/store/Epics.ts
  src/Web/src/components/groups/store/Reducers.ts
  src/Web/src/components/groups/store/Types.ts
Labels: enhancement

#128 feature: [WEB] Usuwanie przejazdu przez ownera
  src/Web/src/api/Helper.ts
  src/Web/src/api/enum/RequestEndpoint.ts
  src/Web/src/components/rides/api/deleteRide/DeleteRideRequest.ts
  src/Web/src/components/rides/api/deleteRide/DeleteRideResponse.ts
  src/Web/src/components/rides/store/Actions.ts
  src/Web/src/components/rides/store/Epics.ts
  src/Web/src/components/rides/store/Types.ts
  src/Web/src/components/shared/ridesList/components/items/ActiveItemOwner.tsx
  src/Web/src/components/shared/ridesList/components/lists/RidesListSchedule.tsx
Labels: enhancement

#131 feature: [WEB] Edycja grupy
  src/Web/src/components/groups/Groups.tsx
  src/Web/src/components/groups/api/updateGroup/UpdateGroupRequest.ts
  src/Web/src/components/groups/components/edit/components/EditGroupForm.tsx
  src/Web/src/components/groups/components/edit/interfaces/IEditGroupFormData.ts
  src/Web/src/components/groups/store/Actions.ts
  src/Web/src/components/groups/store/Epics.ts
  src/Web/src/components/groups/store/Types.ts
  src/Web/src/components/ui/input/Input.tsx
  src/Web/src/translations/pl.json
Labels: enhancement

#135 fix: [WEB] Reguły hasła przy rejestracji
  src/Web/package-lock.json
  src/Web/src/components/auth/login/LoginPanel.tsx
  src/Web/src/components/auth/register/RegisterPanel.tsx
  src/Web/src/components/groups/components/edit/components/EditGroupForm.tsx
  src/Web/src/components/map/MapBoxHelper.ts
  src/Web/src/components/shared/ridesList/components/items/ActiveItemDefault.tsx
  src/Web/src/components/shared/ridesList/components/items/ActiveItemJoin.tsx
  src/Web/src/components/shared/ridesList/components/items/ActiveItemOwner.tsx
  src/Web/src/components/shared/ridesList/components/items/ActiveItemParticipant.tsx
  src/Web/src/components/shared/ridesList/components/items/ActiveItemRequestOwner.tsx
  src/Web/src/components/shared/ridesList/components/items/ActiveItemRequestParticipant.tsx
  src/Web/src/components/shared/ridesList/components/items/DefaultItem.tsx
  src/Web/src/components/shared/ridesList/components/items/DefaultItemRequestOwner.tsx
  src/Web/src/components/shared/ridesList/components/items/DefaultItemRequestParticipant.tsx
  src/Web/src/components/ui/hooks/PasswordInput.tsx
  src/Web/src/components/ui/hooks/usePasswordWithConfirm/UsePasswordWithConfirm.scss
  src/Web/src/components/ui/hooks/usePasswordWithConfirm/UsePasswordWithConfirm.tsx
  src/Web/src/components/ui/input/Input.tsx
  src/Web/src/components/userProfile/components/UserPassword.tsx
  src/Web/src/translations/pl.json
Labels: enhancement

#140 fix: [WEB] Naprawa formularza edycji grup
  src/Web/src/components/groups/components/edit/components/EditGroupForm.tsx
  src/Web/src/components/rides/components/addRide/FirstStep.tsx
  src/Web/src/components/ui/input/Input.tsx
  src/Web/src/components/ui/input/interfaces/IValidation.ts
  src/Web/src/translations/pl.json
Labels: bug

#141 feature: [WEB] Usuwanie pasażerów z przejazdu jako kierowca
  src/Web/src/api/Helper.ts
  src/Web/src/api/enum/RequestEndpoint.ts
  src/Web/src/components/groups/interfaces/IRideStop.ts
  src/Web/src/components/map/MapBoxRides.tsx
  src/Web/src/components/rides/api/deletePassenger/DeletePassengerRequest.ts
  src/Web/src/components/rides/api/deletePassenger/DeletePassengerResponse.ts
  src/Web/src/components/rides/store/Actions.ts
  src/Web/src/components/rides/store/Epics.ts
  src/Web/src/components/rides/store/Types.ts
  src/Web/src/components/shared/ridesList/components/items/ActiveItemOwner.tsx
  src/Web/src/components/shared/ridesList/components/lists/RidesListSchedule.tsx
  src/Web/src/components/ui/input/Input.tsx
Labels: enhancement

#142 feature: [WEB] Czyszczenie store aplikacji po wylogowaniu
  src/Web/src/components/auth/store/Epics.ts
  src/Web/src/components/auth/store/Reducers.ts
  src/Web/src/components/auth/store/State.ts
  src/Web/src/components/auth/store/Types.ts
  src/Web/src/components/groups/store/Reducers.ts
  src/Web/src/components/groups/store/Types.ts
  src/Web/src/components/layout/Layout.tsx
  src/Web/src/components/layout/store/PropsTypes.ts
  src/Web/src/components/layout/store/Reducers.ts
  src/Web/src/components/layout/store/Types.ts
  src/Web/src/components/rides/store/Reducers.ts
  src/Web/src/components/rides/store/Types.ts
  src/Web/src/components/shared/ridesList/components/items/ActiveItemOwner.tsx
  src/Web/src/components/userProfile/store/Reducers.ts
  src/Web/src/components/userProfile/store/Types.ts
Labels: enhancement

#143 CARP-569 Fix invite form to accept only autocompleted mails
  src/Web/src/components/footer/Footer.tsx
  src/Web/src/components/groups/Groups.tsx
  src/Web/src/components/groups/components/invite/GroupInvite.tsx
  src/Web/src/components/groups/components/invite/components/AddInviteForm.tsx
  src/Web/src/components/groups/store/Epics.ts
  src/Web/src/components/groups/store/PropsTypes.ts
  src/Web/src/components/navBar/NavBar.tsx
  src/Web/src/components/ui/autocompleteWrapper/AutocompleteWrapper.tsx
Labels: bug

#144 fix: [WEB] Poprawa walidacji adresu email z autocomplete przy zapraszaniu
  src/Web/src/components/groups/components/invite/components/AddInviteForm.tsx
Labels: bug

#145 improvement: Added stops to ride request get response object
  src/API/RestService/DataAccessLayer/Repositories/RideRequestRepository.cs
  src/API/RestService/RestApi/Queries/RideRequestQueries/GetOwnerRideRequestsQuery.cs
  src/API/RestService/RestApi/Queries/RideRequestQueries/GetParticipantRideRequestsQuery.cs
  src/API/Shared/DataTransferObjects/Ride/RideDtos.cs
  src/API/Shared/DataTransferObjects/User/UserDtos.cs
Labels: enhancement

#149 Feature/web/notifications
  src/Web/src/components/auth/api/login/LoginResponse.ts
  src/Web/src/components/auth/interfaces/ITokenInfo.ts
  src/Web/src/components/auth/store/Epics.ts
  src/Web/src/components/auth/store/Types.ts
  src/Web/src/components/groups/store/Epics.ts
  src/Web/src/components/rides/store/Epics.ts
  src/Web/src/components/userProfile/store/Epics.ts
  src/Web/src/helpers/UniversalHelper.ts
  src/Web/src/translations/pl.json
Labels: enhancement

#157 feature: [WEB] Obsługa zmiany hasła
  src/Web/src/api/Helper.ts
  src/Web/src/api/enum/RequestEndpoint.ts
  src/Web/src/components/userProfile/UserProfile.tsx
  src/Web/src/components/userProfile/api/changePassword/ChangePasswordRequest.ts
  src/Web/src/components/userProfile/api/changePassword/ChangePasswordResponse.ts
  src/Web/src/components/userProfile/components/UserData.tsx
  src/Web/src/components/userProfile/components/UserPassword.tsx
  src/Web/src/components/userProfile/interfaces/IChangePasswordFormData.ts
  src/Web/src/components/userProfile/store/Epics.ts
  src/Web/src/translations/pl.json
Labels: enhancement

#158 fix: [WEB] Poprawka walidacji formularza zmiany hasła
  src/Web/src/components/userProfile/components/UserPassword.tsx
Labels: bug, enhancement

#167 Fix bugs after merge with master
  src/Web/src/components/Hello/Hello.tsx
  src/Web/src/scss/_variables.scss
  src/Web/webpack.config.js
Labels: bug

#168 chore: Fix post-merge bugs
  src/Web/src/components/Hello/Hello.tsx
  src/Web/src/scss/_variables.scss
  src/Web/webpack.config.js
Labels: bug

#171 feature: [WEB] Ride matching and small UI fixes
  src/Web/package-lock.json
  src/Web/package.json
  src/Web/src/api/Helper.ts
  src/Web/src/api/interfaces/IRequestQueries.ts
  src/Web/src/components/footer/Footer.scss
  src/Web/src/components/footer/Footer.tsx
  src/Web/src/components/groups/api/getRides/GetRidesRequest.ts
  src/Web/src/components/groups/components/GroupsRouter.tsx
  src/Web/src/components/groups/components/detailedView/GroupDetailedView.tsx
  src/Web/src/components/groups/components/edit/components/EditGroupForm.tsx
  src/Web/src/components/groups/components/manageScreen/components/groupsList/components/ActiveItem.tsx
  src/Web/src/components/groups/components/manageScreen/components/groupsList/components/LeaveGroupModal.tsx
  src/Web/src/components/groups/components/rides/GroupRides.tsx
  src/Web/src/components/groups/components/users/components/usersList/UserList.tsx
  src/Web/src/components/groups/interfaces/IGroupCallbacks.ts
  src/Web/src/components/groups/interfaces/IRideExtended.ts
  src/Web/src/components/groups/interfaces/IRideFilters.ts
  src/Web/src/components/groups/store/Actions.ts
  src/Web/src/components/groups/store/Epics.ts
  src/Web/src/components/groups/store/PropsTypes.ts
  src/Web/src/components/groups/store/Types.ts
  src/Web/src/components/homeScreen/HomeScreen.scss
  src/Web/src/components/homeScreen/HomeScreen.tsx
  src/Web/src/components/homeScreen/components/HelpBanner.tsx
  src/Web/src/components/rides/components/rides/Rides.tsx
  src/Web/src/components/shared/addressModal/AddressModal.tsx
  src/Web/src/components/shared/ridesList/RidesList.scss
  src/Web/src/components/shared/ridesList/RidesList.tsx
  src/Web/src/components/shared/ridesList/components/items/ActiveItemDefault.tsx
  src/Web/src/components/shared/ridesList/components/items/ActiveItemJoin.tsx
  src/Web/src/components/shared/ridesList/components/items/ActiveItemOwner.tsx
  src/Web/src/components/shared/ridesList/components/items/ActiveItemParticipant.tsx
  src/Web/src/components/shared/ridesList/components/items/ActiveItemRequestOwner.tsx
  src/Web/src/components/shared/ridesList/components/items/ActiveItemRequestParticipant.tsx
  src/Web/src/components/shared/ridesList/components/items/DefaultItem.tsx
  src/Web/src/components/shared/ridesList/components/items/DefaultItemRequestOwner.tsx
  src/Web/src/components/shared/ridesList/components/items/DefaultItemRequestParticipant.tsx
  src/Web/src/components/shared/ridesList/components/lists/RidesListDefault.tsx
  src/Web/src/components/shared/ridesList/components/searchRideModal/SearchRideModal.scss
  src/Web/src/components/shared/ridesList/components/searchRideModal/SearchRideModal.tsx
  src/Web/src/components/shared/ridesList/interfaces/IListProps.ts
  src/Web/src/components/shared/ridesList/interfaces/IRidesItemProps.ts
  src/Web/src/components/shared/ridesList/interfaces/IRidesListProps.ts
  src/Web/src/components/system/FallbackRoute.tsx
  src/Web/src/components/ui/button/Button.scss
  src/Web/src/components/ui/button/Button.tsx
  src/Web/src/components/ui/button/Helpers.ts
  src/Web/src/components/ui/button/enums/ButtonIcon.ts
  src/Web/src/components/ui/hooks/useForceUpdate/UseForceUpdate.tsx
  src/Web/src/components/ui/hooks/usePasswordWithConfirm/UsePasswordWithConfirm.tsx
  src/Web/src/components/ui/input/Input.tsx
  src/Web/src/components/ui/searchBar/SearchBar.tsx
  src/Web/src/components/userProfile/components/UserData.tsx
  src/Web/src/helpers/RidesHelper.ts
  src/Web/src/helpers/StopsHelper.ts
  src/Web/src/translations/pl.json
Labels: enhancement

#175 feature: [WEB] Filtering rides by direction
  src/Web/src/api/interfaces/IRequestQueries.ts
  src/Web/src/components/groups/api/addRide/AddRideRequest.ts
  src/Web/src/components/groups/api/getRides/GetRidesRequest.ts
  src/Web/src/components/groups/store/Epics.ts
  src/Web/src/components/shared/ridesList/RidesList.scss
  src/Web/src/components/shared/ridesList/components/searchRideModal/SearchRideModal.tsx
  src/Web/src/components/ui/checkbox/Checkbox.ts
  src/Web/src/translations/pl.json
Labels: enhancement
